#!/bin/sh
# CRLF conversion utility
# Copyright (C) 1989-2015 Juergen Pfeifer 

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, distribute with modifications, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE ABOVE COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
# THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name(s) of the above copyright
# holders shall not be used in advertising or otherwise to promote the
# sale, use or other dealings in this Software without prior written
# authorization.
#
#
me=$(basename $0)
dir=$(dirname $0)
if [ $# -eq 0 ]; then
    # act as a filter
    case "$me" in
		  "dtou"|"dos2unix")
		      sed -f "${dir}/dtou.sed" || exit $?
		      ;;
		  "utod"|"unix2dos")
		      sed 's/$/\r/g' || exit $?
		      ;;
		  *)  echo Unknown command >&2
		      exit 1
		      ;;
    esac
else
    # process arguments as files
    while [ $# -gt 0 ]; do
	if [ -w "$1" ]; then
	    case "$me" in
		  "dtou"|"dos2unix")
		      sed -i -f "${dir}/dtou.sed" "$1" || exit $?
		      ;;
		  "utod"|"unix2dos")
		      sed -i 's/$/\r/g' "$1" || exit $?
		      ;;
		  *)  echo Unknown command >&2
		      exit 1
		      ;;
	    esac
	else
	    echo $1 not writable >&2
	    exit 1
	fi
	shift
    done
fi
exit 0
